Bug 537354 - NoSuchMethodError in LinuxtoolsPathPropertyPage
- add minimum requirement for org.eclipse.ui requirement so SWT
  will be adequate level

Change-Id: I388c2dbafd60216468ab8f0e64746c3d24255696
Reviewed-on: https://git.eclipse.org/r/126857
Tested-by: CI Bot
Reviewed-by: Jeff Johnston <jjohnstn@redhat.com>
(cherry picked from commit 3dccb18f4f821bfd15b26a7d31358cc42a4ad570)
Reviewed-on: https://git.eclipse.org/r/126861