Bug 538012 - NoSuchMethodError in AbstractProviderPropertyTab
- in createControls, code uses SelectionListener.widgetSelectedAdapter
  which only exists as of SWT 3.106.0
- add bundle requirement to MANIFEST.MF

Change-Id: I24c45c11d7283fa8086bea538000ed92e24527ef
Reviewed-on: https://git.eclipse.org/r/127534
Tested-by: CI Bot
Reviewed-by: Jeff Johnston <jjohnstn@redhat.com>
(cherry picked from commit fc85e8168ef832ac4cfaeb69946ca8fb59cb7e43)
Reviewed-on: https://git.eclipse.org/r/127541