Bug 538184 - NoSuchMethodError in ValgrindOptionsTab
- add SWT minimum version to org.eclipse.linuxtools.valgrind.ui
  to be 3.106

Change-Id: If8b6359ac83b4dd8dd722de8612831b0e47678c6
Reviewed-on: https://git.eclipse.org/r/127884
Tested-by: CI Bot
Reviewed-by: Jeff Johnston <jjohnstn@redhat.com>
(cherry picked from commit 429165f0a8ed2a18cfe504074e96a5ee19974da1)
Reviewed-on: https://git.eclipse.org/r/127885