Bug 537248 - NoClassDefFoundError in ConnectionPropertyTester
- add a try/catch in the test logic of ConnectionPropertyTester
  in case org.eclipse.linuxtools.docker.core hasn't loaded
- do similar for VolumePropertyTester

Change-Id: I69670ac9a6a421cde02361a49e0799e2210fb1f1
Reviewed-on: https://git.eclipse.org/r/126409
Tested-by: CI Bot
Reviewed-by: Jeff Johnston <jjohnstn@redhat.com>
(cherry picked from commit 531977c384e1fecc888e2642532d99ff0ff304bc)
Reviewed-on: https://git.eclipse.org/r/126410