Bug 535781 - [EPP Photon RC3] java.lang.NoClassDefFoundError
- add check for IllegalArgumentException to DockerConnection ping()
  method in case 127.0.0.1 is not set up with a host name

Change-Id: I7f33b193942132f987790b070d98aa0a97d5b302
Reviewed-on: https://git.eclipse.org/r/124371
Tested-by: CI Bot
Reviewed-by: Jeff Johnston <jjohnstn@redhat.com>
(cherry picked from commit b2366f4a815b1e48ec9f0927be6f922faf6dae73)
Reviewed-on: https://git.eclipse.org/r/124372